Week3
Lidemy/mentor-program-5th-andreahsu1030 pull request #3
Opened 2021-05-02 10:27 UTC by andreahsu1030

2021-05-03 10:09 UTC, SimonOneNineEight reviewed
質數那邊還有一點小問題，另外就是變數命名很重要可以注意一下 XDD，訂正完還需要我的話就叫我一聲，不然就自己 merge 吧！

2021-05-03 10:09 UTC, SimonOneNineEight commented on homeworks/week3/hw1.js
> +  for (let k = 1; k <= n; k++) {
let k 還蠻有趣的

2021-05-03 10:09 UTC, SimonOneNineEight commented on homeworks/week3/hw1.js
> +      console.log('*'.repeat(k))
如果 repeat(1) 不會只印出一個 ＊ 嗎？這樣就不用上面的 if 了吧～

2021-05-03 10:09 UTC, SimonOneNineEight commented on homeworks/week3/hw2.js
> +    return result
可以思考看看這邊如果用字串長度來做是不是更快速一點

2021-05-03 10:09 UTC, SimonOneNineEight commented on homeworks/week3/hw2.js
> +    let m = n
這裡讓我們體會到了變數命名的重要性，在這一題裡面你重複用了好多次 m 跟 n 搞得我好糊塗呀～

2021-05-03 10:09 UTC, SimonOneNineEight commented on homeworks/week3/hw3.js
> +      if (lines[i] % j === 0) {
這邊如果數字是 2 的話好像會判合數哦！

2021-05-05 05:23 UTC, cwc329 requested changes
有幾個作業沒有達到要求，
交作業前請確認有沒有達到基本要求。

另外這個 branch 很混亂，
明明是 week3 卻有 week2 的內容，
發 PR 之後請到 Files changed 確認你這次的變動，
如果有太多變動，
可能是你 git 切 branch 沒有處理好。
我建議每次都從 master 切出去交作業。

2021-05-05 05:23 UTC, cwc329 commented on homeworks/week2/hw2.js
> +  var firstWord = str.charCodeAt(0)
word 結果變數型態是 number，這有點怪。

2021-05-05 05:23 UTC, cwc329 commented on homeworks/week2/hw2.js
>  }
string 第一個字元是大寫會被轉成小寫，不符合作業要求。

2021-05-05 05:23 UTC, cwc329 commented on homeworks/week2/hw5.js
>  }
這題沒有達到要求，請重新看題目。

2021-05-05 05:23 UTC, cwc329 commented on homeworks/week2/hw5.js
>  }
這題也不對，請自己測試過後修正。

2021-05-05 05:23 UTC, cwc329 commented on homeworks/week2/hw6.md
> +    13. 跳出迴圈
流程太過簡單，
請一步一步把所有流程寫下，包括 arr[i] 等的值是多少。

2021-05-05 05:23 UTC, cwc329 commented on homeworks/week3/hw3.js
> +}
我複製全部 code 沒有通過 LIOJ，
你確定你有用這份 code 得到 AC 嗎？

2021-05-05 05:23 UTC, cwc329 commented on homeworks/week3/hw5.js
> +}
可以想一下不用 BigInt 要怎麼做。

2021-05-05 05:23 UTC, closed without merging

2021-05-05 05:24 UTC, cwc329 commented
請訂正、重新整理 branch 之後再交一次作業。